name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'  # Solo ejecuta el workflow si hay cambios en el frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: |
        cd frontend  # Ajusta la ruta si tu frontend está en otro directorio
        npm install   # O pnpm install si usas pnpm

    - name: Build frontend
      run: |
        cd frontend
        npm run build  # O el comando que uses para construir tu frontend

    - name: Deploy frontend
      run: |
        cd frontend
        # Agrega el comando de despliegue a tu servidor o servicio (por ejemplo, Docker, Firebase, etc.)
